language: python
python:
  - "2.7"

services:
 #- mysql
 - postgresql
env:
  - DJ=1.8 DB=sqlitememory TEST=main
  - DJ=1.8 DB=sqlitefile   TEST=main
  - DJ=1.8 DB=postgres     TEST=main
#  - DJ=1.9 DB=sqlitememory TEST=main
#  - DJ=1.9 DB=sqlitefile   TEST=main
#  - DJ=1.9 DB=postgres     TEST=main

  - DJ=1.8 DB=sqlitememory TEST=extensions
  - DJ=1.8 DB=sqlitefile   TEST=extensions
  - DJ=1.8 DB=postgres     TEST=extensions
#  - DJ=1.9 DB=sqlitememory TEST=extensions
#  - DJ=1.9 DB=sqlitefile   TEST=extensions
#  - DJ=1.9 DB=postgres     TEST=extensions

  - DJ=1.8 DB=sqlitememory TEST=querysets
  - DJ=1.8 DB=sqlitefile   TEST=querysets
  - DJ=1.8 DB=postgres     TEST=querysets
#  - DJ=1.9 DB=sqlitememory TEST=querysets
#  - DJ=1.9 DB=sqlitefile   TEST=querysets
#  - DJ=1.9 DB=postgres     TEST=querysets

#  - DJ=1.9 DB=mysql
#  - DJ=1.8 DB=mysql

before_install:
  - npm install -g less@1.7.4 # Required for static-precompiler
before_script:
#  - mysql -e 'create database aristotle_test_db;'
  - psql -c 'create database aristotle_test_db;' -U postgres
install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --quiet --use-mirrors; fi
#  - if [[ $DB == mysql ]]; then pip install -q mysql-python --use-mirrors; fi
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install ."
  - pip install -q Django==$DJ --use-mirrors
  - "pip install django_tools"

# command to run tests
script:
  - coverage run --branch --source=aristotle_dse manage.py test aristotle_dse.tests
after_success:
  - coveralls

# Lets run on the new infrastructure
sudo: false

